dracomania_cards = {
    1 : {
        "nome" : "dragão mestre",
        "magia": 22,
        "força": 26,
        "fogo": 29,
    },
    2 : {
        "nome" : "dragão dourado",
        "magia": 16,
        "força": 24,
        "fogo": 28,
    },
    3 : {
        "nome" : "dragão prateado",
        "magia": 15,
        "força": 21,
        "fogo": 27,
    },
    4 : {
        "nome" : "dragão bronze",
        "magia": 14,
        "força": 20,
        "fogo": 26,
    },
    5 : {
        "nome" : "dragão cobre",
        "magia": 13,
        "força": 19,
        "fogo": 25,
    },
    6 : {
        "nome" : "dragão branco",
        "magia": 21,
        "força": 15,
        "fogo": 22,
    },
    7 : {
        "nome" : "dragão negro",
        "magia": 19,
        "força": 17,
        "fogo": 24,
    },
    8 : {
        "nome" : "dragão vermelho",
        "magia": 20,
        "força": 16,
        "fogo": 23,
    },
    9 : {
        "nome" : "dragão azul",
        "magia": 18,
        "força": 13,
        "fogo": 21,
    },
    10 : {
        "nome" : "dragão verde",
        "magia": 17,
        "força": 14,
        "fogo": 20,
    },
    11 : {
        "nome" : "cavaleiro",
        "magia": 6,
        "força": 23,
        "fogo": 11,
    },
    12 : {
        "nome" : "colosso",
        "magia": 0,
        "força": 30,
        "fogo": 0,
    },
    13 : {
        "nome" : "feiticeira",
        "magia": 28,
        "força": 2,
        "fogo": 19,
    },
    14 : {
        "nome" : "guerreira",
        "magia": 5,
        "força": 22,
        "fogo": 9,
    },
    15 : {
        "nome" : "guerreiro",
        "magia": 4,
        "força": 25,
        "fogo": 8,
    },
    16 : {
        "nome" : "herói",
        "magia": 12,
        "força": 27,
        "fogo": 15,
    },
    17 : {
        "nome" : "lobisomem",
        "magia": 11,
        "força": 18,
        "fogo": 10,
    },
    18 : {
        "nome" : "mago",
        "magia": 29,
        "força": 4,
        "fogo": 17,
    },
    19 : {
        "nome" : "merlin",
        "magia": 30,
        "força": 0,
        "fogo": 0,
    },
    20 : {
        "nome" : "múmia",
        "magia": 9,
        "força": 9,
        "fogo": 3,
    },
    21 : {
        "nome" : 'pegasus',
        "magia": 23,
        "força": 12,
        "fogo": 12,
    },
    22 : {
        "nome" : "sacerdote",
        "magia": 26,
        "força": 5,
        "fogo": 18,
    },
    23 : {
        "nome" : "sombra",
        "magia": 8,
        "força": 7,
        "fogo": 1,
    },
    24 : {
        "nome" : "bárbaro",
        "magia": 3,
        "força": 29,
        "fogo": 5,
    },
    25 : {
        "nome" : "viking",
        "magia": 2,
        "força": 28,
        "fogo": 6,
    },
    26 : {
        "nome" : "bruxa",
        "magia": 27,
        "força": 3,
        "fogo": 16,
    },
    27 : {
        "nome" : "elfo",
        "magia": 25,
        "força": 6,
        "fogo": 14,
    },
    28 : {
        "nome" : "anjo",
        "magia": 24,
        "força": 1,
        "fogo": 7,
    },
    29 : {
        "nome" : "gigante de lava",
        "magia": 0,
        "força": 0,
        "fogo": 30,
    },
    30 : {
        "nome" : "esqueleto",
        "magia": 7,
        "força": 8,
        "fogo": 2,
    },
    31 : {
        "nome" : "ogro",
        "magia": 1,
        "força": 10,
        "fogo": 4,
    },
    32 : {
        "nome" : "unicórnio",
        "magia": 10,
        "força": 11,
        "fogo": 13,
    },
}